### ISSUE TITLE
Make ""I WILL NOT USE THIS TO STORE FORMIK STATE ELSEWHERE IN MY APP."" more precise

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [jaredpalmer/formik-effect#8]
Could you explain what 

"I WILL NOT USE THIS TO STORE FORMIK STATE ELSEWHERE IN MY APP."

actually means?

F.e. I would like to use effects to make a realtime search, where you enter a search query and get below a list of results (triggered via redux / redux-observable) - therefore I need to use the onChange event, which is not included in formik as it seems - but in this addon?

Is my desired behaviour not recommended? :D

**Comment by jaredpalmer** [comment]
Trying to store interim Formik state (i.e. anything but initialValues and the values you get back from onSubmit) will inevitably fail.
